kartoza_technical_assignment/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import include, path
from user_authentication import views as user_auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_profile.urls')),
    
    # AUTHENTICATION URLS
    path('sign-up/', user_auth_views.user_sign_up, name="register"),
    path('sign-in/', auth_views.LoginView.as_view(template_name="user_authentication/user_sign_in.html"), name="login"),
    path('sign-out/', auth_views.LogoutView.as_view(template_name="user_authentication/user_sign_out.html"), name="logout"),

    # REST FRAMEWORK URLS
    path('api/', include('user_profile.api.urls')), 
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/api/urls.py
from django.urls import path
from user_profile.api import views

urlpatterns = [
    path('users/', views.api_users_view, name="users"),
    path("current-user/",views.api_authenticated_user_view, name="current-user")
]

user_profile/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
	path('user-profile/', views.user_profile, name="user_profile"),
    path('edit-user-profile/', views.edit_user_profile, name="edit_user_profile"),   
]

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user            = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    profile_picture = models.ImageField(default="default_user_profile.png", upload_to="profile_pictures")
    profession      = models.CharField(max_length=100, null=True, blank=False)
    phone_number    = models.CharField(max_length=32, null=True, blank=False)
    website_url     = models.URLField(max_length=255, null=True, blank=True)
    
    address          = models.CharField(max_length=255, null=True, blank=False)
    latitude         = models.FloatField(null=True, blank=True)
    longitude        = models.FloatField(null=True, blank=True)

    # This field will only be True if the address entered by the user is valid
    address_is_valid = models.BooleanField(default=False) 

    class Meta: 
        verbose_name        = "User Profile"
        verbose_name_plural = "User Profiles"

    def __str__(self):
        return "{}'s profile".format(self.user.username)

user_profile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import fields
from .models import UserProfile

class UserUpdateForm(forms.ModelForm):

    class Meta:
        model  = User
        fields = ["first_name", "last_name", "email"]

class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model   = UserProfile
        fields  = "__all__"
        exclude = ["user"]

user_profile/api/views.py
from rest_framework.response import Response
from rest_framework.decorators import api_view

from user_profile.models import User
from user_profile.api.serializers import UserSerializer


@api_view(["GET",])
def api_users_view(request):
    # Return only users with valid addresses to be listed on full page map
    queryset = User.objects.filter(profile__address_is_valid=True)
    
    if request.method == "GET":
        serializer = UserSerializer(queryset, many=True)
        return Response(serializer.data)


@api_view(["GET",])
def api_authenticated_user_view(request):

    if request.method == "GET":
        serializer = UserSerializer(request.user)
        return Response(serializer.data)

user_profile/views.py
import requests
from django.conf import settings 
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm, UserProfileUpdateForm


# Home page with full screen map containing all users
def index(request):
    template = "user_profile/full_page_map.html"
    return render(request, template)


# User profile
@login_required
def user_profile(request):
    template = "user_profile/user_profile_page.html"
    return render(request, template)


# Edit user profile
@login_required
def edit_user_profile(request):

    if request.method == "POST":
        user_update_form         = UserUpdateForm(request.POST, instance=request.user)
        user_profile_update_form = UserProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if user_update_form.is_valid() and user_profile_update_form.is_valid():
            user_update_form.save()
            user_profile = user_profile_update_form.save(commit=False)

            address = request.POST['address']
            status  = extract_lat_lng(address, user_profile)

            # Check status returned by the Google Geocoding API and return message to user accordingly
            if status == "OK":
                messages.success(request, "Your profile has been successfully updated!")
                return redirect('user_profile')

            elif status == "ZERO_RESULTS":
                messages.warning(request, "No results returned, please check if address entered exists and try again.")
                return redirect('edit_user_profile')
            
            elif status == "OVER_DAILY_LIMIT":
                messages.error(
                    request, 
                    """
                    Error, this could be because of missing or invalid API key, 
                    billing has not been enabled on your account, 
                    a self-imposed usage cap has been exceeded or 
                    your provided method of payment is no longer valid (for example, a credit card has expired).
                    """
                    )
                return redirect('edit_user_profile')

            elif status == "OVER_QUERY_LIMIT":
                messages.error(request, "Error, you are over your quota")
                return redirect('edit_user_profile')

            elif status == "REQUEST_DENIED":
                messages.error(request, "Error, request denied.")
                return redirect('edit_user_profile')

            elif status == "INVALID_REQUEST":
                messages.error(request, "Error, query (address, components or latlng) is missing")
                return redirect('edit_user_profile')

            else:
                messages.error(request, "Error, request could not be processed due to a server error, please try again.")
                return redirect('edit_user_profile')

    else:
        user_update_form         = UserUpdateForm(instance=request.user)
        user_profile_update_form = UserProfileUpdateForm(instance=request.user.profile)

    context  = {
       "user_update_form": user_update_form,
       "user_profile_update_form":user_profile_update_form
    }

    template = "user_profile/edit_user_profile_page.html"
    return render(request, template, context)


# extract latitude and longitude from Geocoding API using user's address
def extract_lat_lng(address, user_profile):
    api_key   = settings.API_KEY
    endpoint  = f"https://maps.googleapis.com/maps/api/geocode/json?"
    params    = {
        "address": address,
        "key"    : api_key
    }

    response = requests.get(endpoint, params=params).json()
    status   = response["status"]

    if status == "OK":
        geometry           = response["results"][0]["geometry"]
        user_profile.latitude  = geometry["location"]["lat"]
        user_profile.longitude = geometry["location"]["lng"]
        user_profile.address_is_valid = True
        user_profile.save()
        return status

    else:
        return status
  



    

 

user_profile/templates/user_profile/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'user_profile/css/style.css' %}">
        <title>
            {% if user.first_name and user.last_name %}
                {{ user.get_full_name }} || Kartoza Technical Assignment
                
            {% elif user.username %}
                {{ user.username }} || Kartoza Technical Assignment

            {% else %}
                Kartoza Technical Assignment
            {% endif %} 
        </title>

        <style>
            html, body { 
                height:100%; 
                width:100%;
                overflow-y: hidden; 
                overflow-x: hidden; 
            }

            .resume-btn {
                width: 100%; 
                box-shadow: 0px 8px 16px #15151541, 0px 2px 4px #15151541;
            }
        </style>

        <!-- Extra css block -->
        {% block extra_css %}{% endblock %}
    </head>
    <body>
        <!-- map -->
        {% block full_screen_map %}{% endblock %}

        <div class="container my-5" style="max-width: 700px;">
            <!-- Navbar -->
            {% include 'user_profile/include/navbar.html' %}

            <!-- Alert Messages-->
            {% if messages %}
                <div class="row">
                    {% for message in messages %}
                        {% if message.tags == "error" %}
                            <div class="col-12">
                                <div class="alert alert-danger" role="alert">
                                    {{ message }}
                                </div>
                            </div>
                        {% else %}
                            <div class="col-12">
                                <div class="alert alert-{{ message.tags }}" role="alert">
                                    {{ message }}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>  
            {% endif %}
            
            <!-- Content block -->
            {% block content %}{% endblock %}
        </div>

        {# JavaScript #}
        <!-- Axios -->
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
       
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
        
        <!--  Extra JavaScript block -->
        {% block extra_js %}{% endblock %}

        <!-- Async script executes immediately and must be after any DOM elements used in callback. -->
        <script src="https://maps.googleapis.com/maps/api/js?key=YOUR GOOGLE API KEY GOES HERE&libraries=places&callback=initMap"async></script>
    </body>
</html>

user_profile/templates/user_profile/edit_user_profile_page.html
{% extends 'user_profile/base.html' %}
{% load widget_tweaks static %}

{% block content %}
    <div class="row"> 
        <div class="col-12">
            <div class="card" style="width: 100%;">
                <div class="card-body">
                    <!-- <h4 class="card-title">Edit Profile  <button class="btn btn-primary btn-sm" type="submit">Save changes</button></h4> -->
                    <form action="{% url 'edit_user_profile' %}" class="row" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="col-3">
                            <div class="col-12 mb-2">
                                <img src="{{ user.profile.profile_picture.url }}" id="profile-picture" style="width:100%; height:143px">
                                <label for="id_profile_picture" class="btn btn-dark btn-sm my-2" style="width: 100%;">upload image</label>
                                <input type="file" name="profile_picture" accept="image/*" class="form-control form-control-sm" id="id_profile_picture" hidden>
                            </div>
                        </div>

                        <div class="col-9">
                            <div class="row">
                                <!-- First Name & Last Name-->
                                <div class="col-4 mb-2">
                                    <label lass="form-label">First Name</label>
                                    {% render_field user_update_form.first_name class="form-control form-control-sm" %}
                                </div>
                                <!-- Last Name -->
                                <div class="col-4 mb-2">
                                    <label lass="form-label">Last Name</label>
                                    {% render_field user_update_form.last_name class="form-control form-control-sm" %}
                                </div>
                                <!-- Profession -->
                                <div class="col-4 mb-2">
                                    <label lass="form-label">Profession</label>
                                    {% render_field user_profile_update_form.profession class="form-control form-control-sm" %}
                                </div>
                                <!-- Phone -->
                                <div class="col-6 mb-2">
                                    <label lass="form-label">Phone</label>
                                    {% render_field user_profile_update_form.phone_number class="form-control form-control-sm" %}
                                </div>
                                <!-- Email -->
                                <div class="col-6 mb-2">
                                    <label lass="form-label">Email</label>
                                    {% render_field user_update_form.email class="form-control form-control-sm" %}
                                </div>
                                <!-- Address -->
                                <div class="col-12 mb-2">
                                    <label lass="form-label">Address</label>
                                    {% render_field user_profile_update_form.address class="form-control form-control-sm" %}
                                </div>
                                <!-- Latitude -->
                                <div class="col-3 mb-2" style="display:none">
                                    <label lass="form-label">Latitude</label>
                                    {% render_field user_profile_update_form.latitude class="form-control form-control-sm" %}
                                </div>
                                <!-- Longitude -->
                                <div class="col-3 mb-2" style="display:none">
                                    <label lass="form-label">Longitude</label>
                                    {% render_field user_profile_update_form.longitude class="form-control form-control-sm" %}
                                </div>
                            </div>
                        </div>

                        <div class="col-12">
                            <!-- Mapbox -->
                            <div class="map" id="map" style="width:100%; height:190px"></div>
                        </div>

                        <hr>
                        <!-- buttons -->
                        <div class="col-6">
                            <a href="{% url 'user_profile' %}" class="btn btn-secondary btn-sm">Back to profile page</a>
                        </div>
                        <div class="col-6">
                            <button type="submit" class="btn btn-primary btn-sm" style="float: right;">Save changes</button>
                        </div>
                    </form>
                </div>

                
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <!-- Image upload preview script -->
    <script>
        const uploadButton = document.getElementById('id_profile_picture');
        const imageTag     = document.getElementById('profile-picture');

        uploadButton.addEventListener('change', function() {
            imageTag.src = URL.createObjectURL(this.files[0])
        })
    </script>

    <!-- Custom js -->
    <script src="{% static 'user_profile/js/auto-complete.js' %}"></script>
    <script src="{% static 'user_profile/js/user-profile-map.js' %}"></script>
{% endblock %}


        

user_profile/templates/user_profile/full_page_map.html
{% extends 'user_profile/base.html' %}
{% load static %}

{% block extra_css %}
    <style>
        #map {
            width:100%;
            height:100%;
            position: absolute;
        }
    </style>
{% endblock %}

{% block full_screen_map %}
    <div class="map" id="map"></div>
{% endblock %}

{% block extra_js %}
    <!-- Custom js -->
    <script src="{% static 'user_profile/js/all-users-map.js' %}"></script>
{% endblock %}

user_profile/templates/user_profile/user_profile_page.html
{% extends 'user_profile/base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <!-- User profile picture card col -->
        <div class="col-4">
            <div class="card" style="width:100%; height:450px;">
                <img class="card-img-top" src="{{ user.profile.profile_picture.url }}" height="200px">
                <div class="card-body text-center">
                    {% if user.first_name and user.last_name %}
                        <h2 class="card-title"><b>{{ user.get_full_name }}</b></h2>
                    {% else %}
                        <h2 class="card-title"><b>{{ user.username }}</b></h2>
                    {% endif %}
                    <h5>
                        {% if user.profile.profession %}
                            <span class="text-muted">{{ user.profile.profession }}</span>
                        {% else %}
                            <i class="text-muted"><a href="{% url 'edit_user_profile' %}">what is your profession?</a></i>
                        {% endif %}
                    </h5>
                </div>
                
                <div class="card-body">
                    <a href="{% if user.profile.phone_number %} tel:{{ user.profile.phone_number }} {% else %}#{% endif %}">
                        <button type="button" class="btn btn-dark btn-lg btn-block resume-btn">
                            <span style="font-weight: 400; padding-left: 5px;">Hire Me</span>
                        </button>
                    </a>
                </div>
            </div>
        </div>
        
        <!-- Contact details card col -->
        <div class="col-8">
            <div class="card" style="width:100%; height:450px;">
                <!-- Mapbox -->
                <div class="map" id="map"></div>

                <!-- Contact Details -->
                <div class="card-body">
                    <h4 class="card-title">Contact Details</h4>
                    <h6 class="card-subtitle mb-2 text-muted">
                        {% if user.profile.address %}
                            <i class="fas fa-map-marker-alt"></i> 
                            {{ user.profile.address }}
                        {% else %}
                            <i class="fas fa-map-marker-alt"></i> 
                            <i><a href="{% url 'edit_user_profile' %}">what is your address?</a></i>
                        {% endif %}
                    </h6>
                    <small class="text-success"><i>latitude: {{ user.profile.latitude }}, longitude: {{ user.profile.longitude }}</i></small>

                    <!-- row -->
                    <div class="row mt-3">
                        <div class="col-12">
                            <span>
                                {% if user.profile.phone_number %}
                                    <i class="fas fa-mobile-alt"></i> 
                                    {{ user.profile.phone_number }}
                                {% else %}
                                    <i class="fas fa-mobile-alt text-muted"></i> 
                                    <i class="text-muted"><a href="{% url 'edit_user_profile' %}">what is your phone number?</a></i>
                                {% endif %}
                            </span>
                        </div>
                        <div class="col-12 my-1">
                            <span>
                                {% if user.email %}
                                    <i class="fas fa-envelope"></i> 
                                    {{ user.email }}
                                {% else %}
                                    <i class="fas fa-envelope text-muted"></i> 
                                    <i class="text-muted"><a href="{% url 'edit_user_profile' %}">what is your email address?</a></i>
                                {% endif %}
                            </span>
                        </div>
                        <div class="col-12 my-1">
                            {% if user.profile.website_url %}
                                <span><i class="fas fa-globe"></i> {{ user.profile.website_url }}</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="lat-lng" lat="{{ user.profile.latitude }}" lng="{{ user.profile.longitude }}"></div>
{% endblock %}


{% block extra_js %}
    <!-- Custom js -->
    <script src="{% static 'user_profile/js/user-profile-map.js' %}"></script>
{% endblock %}